### PR TITLE
fix(security): avoid password leaks on query logs

### LINKED ISSUE #5560: DB passwords can be accidentally leaked through logs
**Disclaimer:** I'm reporting this problem here because there are no public policies on how to report security problems. I would have preferred doing this privately.

# Environment

Knex version: 2.4.2
Database + version: MySQL, PostgreSQL, MSSQL (I didn't test with others. DB version does not have any effect)
OS: Mac OS X, Linux

# Bug

1. Explain what kind of behaviour you are getting and how you think it should do:
   ```typescript
   const query = knex('myTable').select('*');
   logger.debug({ query }) // passwords are leaked here
   
   // For a more realistic case:
   try {
     const result = await query
     return result
   } catch (err) {
     logger.error({ err, query }, 'Unknown Error while performing query') // passwords are leaked here
   }
   ```
   The previous code should not leak passwords through the logs, but it does 😢 .
   In our case, the logger was Pino, this problem doesn't necessarily happen with other loggers (as they might use different
   serialisation methods).

3. Error message: There is no error message

4. Reduced test code:
   ```typescript
   // This new test could be placed in `test/integration2/query/misc/additional.spec.js`
   it('should not leak passwords when logged', async function () {
      const util = require('util')
      const query = knex('test_table_two').select('*');
      const fakeLog = util.inspect(query, { depth: null });
      const passwordMatches = fakeLog.match(
        /(knextest|testpassword|S0meVeryHardPassword|testrootpassword)/g
      );

      expect(passwordMatches).to.be.null;
   });
   ```

### PR DESCRIPTION
**Pull request by castarco**
## Motivation:
We detected that under certain conditions, passwords could be leaked through logs, when executing code such as:
```typescript
const query = knex('myTable').select('*');
logger.debug({ query }) // passwords are leaked here
```
In our case, the logger was `Pino`, this problem doesn't necessarily happen with other loggers (as they might use different
serialisation methods).

## Fixes:
- password fields are not leaked anymore. Fixes #5560 .
- accepts configuration objects where the password field exists but it is non-enumerable (this might happen when lib users are trying to prevent the same previous problem, but at a higher level).

## Changes:
- marks the password field as non-enumerable when possible, to avoid potential leaks through logs.
- adapts tests
- add new regression test

### CODE REVIEW

**Comment by castarco** [comment]
Hi @tgriesser , I'm sorry for adding a direct mention, but I have the feeling that this PR fixes a serious issue, and it can be easy that this PR gets lost among the dozens of automated PRs produced by bots.

File: lib/client.js [hunk 1]
```diff
@@ -43,6 +43,13 @@ class Client extends EventEmitter {
     this.config = config;
     this.logger = new Logger(config);
 
+    if (config.connection.password) {
+      Object.defineProperty(config.connection, 'password', {
+        enumerable: false,
+        value: config.connection.password,
+      });
```
Comment (OlivierCavadenti) [inline lib/client.js:50]: Put that inside a global function and use it everywhere please

**Comment by OlivierCavadenti** [comment]
@castarco Thanks for the PR by the way, the error is on the "master" branch and not in your PR.

**Comment by castarco** [comment]
Thanks @OlivierCavadenti  😃 , I was investigating now what I might have broken. It will save me some time!

File: lib/util/security.js [hunk 2]
```diff
@@ -0,0 +1,26 @@
+/**
+ * Sets a hidden (non-enumerable) property on the `target` object, copying it
+ * from `source`.
+ *
+ * This is useful when we want to protect certain data to be accidentally leaked
```
Comment (castarco) [inline lib/util/security.js:5]: I'll fix the grammatical error here

File: test/integration2/query/misc/additional.spec.js [hunk 3]
```diff
@@ -1400,6 +1422,16 @@ describe('Additional', function () {
             expect(knexDb.client.pool.destroyed).to.equal(false);
           });
         });
+
+        it('should not leak passwords when logged', async function () {
+          const query = knex('test_table_two').select('*');
+          const fakeLog = util.inspect(query, { depth: null });
+          const passwordMatches = fakeLog.match(
+            /(knextest|testpassword|S0meVeryHardPassword|testrootpassword)/g
```
Comment (castarco) [inline test/integration2/query/misc/additional.spec.js:1430]: Should I add a comment pointing to the origin of these passwords?

File: lib/util/security.js (hunk 2 above)
Comment (castarco) [reply lib/util/security.js]: Done

**Comment by castarco** [comment]
Any news on whether this will be approved/rejected/merged? From our side it's not urgent, because we are using `yarn patch` in our project, but this PR fixes a vulnerability that can affect other people...

**Comment by Eomm** [comment]
@OlivierCavadenti any update on this?

**Review by OlivierCavadenti — APPROVED** [review]

**Comment by OlivierCavadenti** [comment]
@Eomm sorry for the delay.
I will release a new version as soon as possible (this week), but I need time to also check documentation.
Stay tuned :D

**Comment by daniellockyer** [comment]
Is it possible that this has broken auth in 2.5.0? We've started to get auth issues for the 2.4.0 -> 2.5.0 Knex bump in Ghost: https://github.com/TryGhost/Ghost/actions/runs/5505546016/jobs/10033054604?pr=17254#step:11:283

```
  Error: Access denied for user 'root'@'172.17.0.1' (using password: NO)
      at /home/runner/work/Ghost/Ghost/node_modules/knex-migrator/lib/database.js:176:39
      at Packet.asError (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/packets/packet.js:728:17)
      at ClientHandshake.execute (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/commands/command.js:29:26)
      at Connection.handlePacket (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/connection.js:489:32)
      at PacketParser.onPacket (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/connection.js:94:12)
      at PacketParser.executeStart (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/packet_parser.js:75:16)
      at Socket.<anonymous> (/home/runner/work/Ghost/Ghost/node_modules/mysql2/lib/connection.js:101:25)
      at Socket.emit (node:events:390:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by OlivierCavadenti** [comment]
Hi, can you check this @castarco ? https://github.com/knex/knex/issues/5629

**Comment by castarco** [comment]
I'll check. It could be related.

**Comment by OlivierCavadenti** [comment]
> I'll check. It could be related.

Thanks !

**Comment by elszczepano** [comment]
> Is it possible that this has broken auth in 2.5.0? We've started to get auth issues for the 2.4.0 -> 2.5.0 

Yes, it looks exactly the same as in my case 😄

**Comment by castarco** [comment]
I didn't had time this past night to fix it as I was lower on energy, but I was walking through the code and I already have some idea of how to fix it. Hopefully today I'll be able to post a patch.

**Comment by OlivierCavadenti** [comment]
> I didn't had time this past night to fix it as I was low on energy, but I was walking through the code and I already have some idea of how to fix it. Hopefully today I'll be able to post a patch.
> 
> Again, sorry for the disturbance.

No problem, we all deal with our personal life, do as you can

**Comment by idandagan1** [comment]
Hi, 
I used to pass the db connection password using the package "config" with custom variables from outside the app.

But after upgrading to v2.5.0, it fails with the error:
```
Cannot redefine property: password
TypeError: Cannot redefine property: password
    at Function.defineProperty (<anonymous>)
    at setHiddenProperty 
```
So what's your suggestion for injecting the password?

**Comment by Fryuni** [comment]
Just as a note, this broke our integrations tests since we now cannot reuse the same object with the configurations between scenarios.

We have to clone the object for each instantiation of knex otherwise we get `SCRAM-SERVER-FIRST-MESSAGE: client password must be a string` from all but the first instantiation.

Easy fix on our side, but just registering here so other might know.

**Comment by bertho-zero** [comment]
This is a bad PR, the original object is modified and the password is lost.
