### PR TITLE
Prevent unexpected combinations of statements and clauses groups from executing

### LINKED ISSUE #4070: knex('table').having({ field: 'value' }).del() silently deletes ALL rows!
# Environment

Knex version: 0.21.5
Database + version: postgres 13.0
OS: alpine

# Bug

Explain what kind of behaviour you are getting and how you think it should do:

running
``` javascript
knex('table').having('some_relation_count', '>', 0).del()
```
silently removes "having" and results in
``` sql
delete from "table"
```
I executed a similar select query to check the effected rows and then executed the delete query.
fortunately I had backups!

I think knex could throw an error or let the database throw a syntax error by not removing the "having" part
Thank you for this great project

### PR DESCRIPTION
**Pull request by myndzi**
Fixes #4070, #6074

Clauses such as "HAVING" and "WHERE" have no effect on "DELETE" or "TRUNCATE" statements. Due to the architecture of knex, dialects override various base methods for building specific statements. The methods implementing these statements don't explicitly check for the presence of clauses that a user might expect to have an effect, but there isn't a good place to ensure that such queries fail systematically.

This commit introduces a "_preValidate" method on the root QueryCompiler class and a set of disallowed verb/clause combinations that will throw an error before doing any SQL-building work. This should make it consistent to prevent anything like `knex.having(...).del()` from unintentionally deleting all rows.

The current configuration disallows "HAVING" from "DELETE" statements, and both "WHERE" and "HAVING" from "TRUNCATE" statements.

Update:
Now also rejects "LIMIT" from "DELETE" and "TRUNCATE"

DRI:@myndzi

### CODE REVIEW

**Comment by myndzi** [comment]
(This needs a re-run of the one CI task - it failed on a network error updating coveralls)

File: lib/query/querycompiler.js [hunk 1]
```diff
@@ -1,6 +1,7 @@
 // Query Compiler
 // -------
 const helpers = require('../util/helpers');
+const HOP = require('../util/security').hasOwnProperty;
```
Comment (kibertoad) [inline lib/query/querycompiler.js]: It would be preferable to avoid non-obvious abbreviations

File: lib/query/querycompiler.js [hunk 2]
```diff
@@ -66,8 +77,44 @@ class QueryCompiler {
...
+    const verb = HOP.call(methodAliases, method)
+      ? methodAliases[method]
+      : method;
+    if (!HOP.call(invalidClauses, verb)) return;
+
+    // For certain verbs, certain clauses just don't exist / aren't supported. The list
+    // here is intentionally not complete; it's just checking the things that allow users
+    // to make dangerous errors.
+    const invalid = invalidClauses[verb];
+    for (let i = 0; i < invalid.length; i++) {
```
Comment (kibertoad) [inline lib/query/querycompiler.js:96]: why not use for of?

File: lib/query/querycompiler.js [hunk 3]
```diff
@@ -66,8 +77,44 @@ class QueryCompiler {
...
+      const clause = invalid[i];
+
+      const hasNonEmptyGrouped =
+        HOP.call(this.grouped, clause) && this.grouped[clause].length > 0;
+      const hasNonEmptySingle =
+        HOP.call(this.single, clause) && this.single[clause] != null;
+
+      if (hasNonEmptyGrouped || hasNonEmptySingle) {
+        throw new Error(
+          `Refused to compile query: \`${clause}\` has no effect on a \`${verb}\` statement`
```
Comment (kibertoad) [inline lib/query/querycompiler.js]: Wording is a bit confusing, "Refused" can mean many things. I'd suggest making it more explicit by saying that query compilation was aborted because part of it would have had no effect

File: lib/util/security.js [hunk 4]
```diff
@@ -21,6 +21,9 @@ function setHiddenProperty(target, source, propertyName = 'password') {
   });
 }
 
+const hasOwnProperty = Object.prototype.hasOwnProperty;
```
Comment (kibertoad) [inline lib/util/security.js]: I'm not sure it's a good idea to do this reexport. the fact that it needs to be invoked via ".call" is not obvious.

helper function wpuld be clearer:

function hasOwn(obj, key) {
  return Object.prototype.hasOwnProperty.call(obj, key);
}

File: lib/query/querycompiler.js (hunk 2 above)
Comment (myndzi) [reply lib/query/querycompiler.js:96]: Combination of:
- presuming it's a hot path, so avoiding extra garbage and/or cpu overhead generated by the iterator protocol
- this loop pattern is generally so recognizable that I don't expect it to be a legibility disadvantage

File: lib/util/security.js (hunk 4 above)
Comment (myndzi) [reply lib/util/security.js]: I just find myself typing it so often that I wanted to make it more easy to access. This is fine too; the main thing is that I want to capture the value of `hasOwnProperty` at load time, which slightly reduces the risk that it gets monkey patched by something (or potentially exploited). I can do that and still export a function.

Once we go beyond node 16 as minimum version we can just use Object.hasOwn anyway

File: lib/query/querycompiler.js (hunk 3 above)
Comment (myndzi) [reply lib/query/querycompiler.js]: How about "Aborted query compilation: ${clause} has no effect on a ${verb} statement"?

I want to include both the thing they tried to add (e.g. `having`) and the statement they tried to add it to (e.g. `delete`) so that it's clear to the user what the problem is.  I would like to avoid general language like "part of it would have had no effect" (what part? what query?), and also make it clear that it was an intentional choice by the library (I "refused" to do what you asked, and here's why)

File: lib/query/querycompiler.js (hunk 2 above)
Comment (myndzi) [reply lib/query/querycompiler.js:96]: Let me know if you'd prefer I changed this

**Comment by myndzi** [comment]
(rebased onto master)
